# Generated by Django 5.1.7 on 2025-03-09 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='max_exposure_minutes',
            field=models.PositiveIntegerField(default=15, verbose_name='Tempo Máximo (minutos)'),
        ),
    ]
